# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-28 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_oauthqquser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthqquser',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='oauthqquser',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
